import type { GeometryRequest } from '../geometry/types'
import type { NumberParameterDefinition, ParameterValues, ParametricModelDefinition } from '../parametric/types'

export type CylinderParameterValues = ParameterValues & {
  height: number
  diameter: number
  wallThickness: number
}

const cylinderParameters: readonly NumberParameterDefinition[] = [
  {
    id: 'height',
    label: 'Height',
    description: 'Overall height of the cylinder.',
    type: 'number',
    unit: 'mm',
    min: 10,
    max: 300,
    step: 1,
  },
  {
    id: 'diameter',
    label: 'Diameter',
    description: 'Outside diameter of the cylinder.',
    type: 'number',
    unit: 'mm',
    min: 10,
    max: 200,
    step: 1,
  },
  {
    id: 'wallThickness',
    label: 'Wall thickness',
    description: 'Material thickness around the through-hole.',
    type: 'number',
    unit: 'mm',
    min: 0.5,
    max: (values) => Math.max(0.5, Number(values.diameter) / 2 - 0.1),
    step: 0.5,
  },
]

const createCylinderRequest = (parameters: ParameterValues): GeometryRequest => ({
  backend: 'replicad',
  operation: 'parametric-cylinder',
  parameters,
})

export const parametricCylinder: ParametricModelDefinition<CylinderParameterValues> = {
  id: 'parametric-cylinder',
  name: 'Parametric Cylinder',
  category: 'Primitives',
  description: 'A hollow, printable cylinder generated by Replicad.',
  parameters: cylinderParameters,
  defaults: {
    height: 80,
    diameter: 50,
    wallThickness: 3,
  },
  generation: {
    backend: 'replicad',
    operation: 'parametric-cylinder',
    generate: createCylinderRequest,
  },
}
