import type { GeometryRequest } from '../geometry/types'
import type {
  NumberParameterDefinition,
  ParameterValues,
  ParametricModelDefinition,
  ValidationResult,
} from '../parametric/types'

export type CylinderParameterValues = ParameterValues & {
  height: number
  diameter: number
  wallThickness: number
}

const cylinderParameters: readonly NumberParameterDefinition[] = [
  {
    id: 'height',
    label: 'Height',
    description: 'Overall height of the cylinder.',
    type: 'number',
    unit: 'mm',
    min: 10,
    max: 300,
    step: 1,
  },
  {
    id: 'diameter',
    label: 'Diameter',
    description: 'Outside diameter of the cylinder.',
    type: 'number',
    unit: 'mm',
    min: 10,
    max: 200,
    step: 1,
  },
  {
    id: 'wallThickness',
    label: 'Wall thickness',
    description: 'Material thickness around the through-hole.',
    type: 'number',
    unit: 'mm',
    min: 0.5,
    max: (values) => Math.max(0.5, Number(values.diameter) / 2 - 0.1),
    step: 0.5,
  },
]

const cylinderDefaults: CylinderParameterValues = {
  height: 80,
  diameter: 50,
  wallThickness: 3,
}

const createCylinderRequest = (parameters: CylinderParameterValues): GeometryRequest => ({
  backend: 'replicad',
  operation: 'parametric-cylinder',
  parameters,
})

function validateCylinder(parameters: CylinderParameterValues): ValidationResult {
  const errors: string[] = []
  const height = Number(parameters.height)
  const diameter = Number(parameters.diameter)
  const wallThickness = Number(parameters.wallThickness)

  if (!Number.isFinite(height) || height < 10 || height > 300) {
    errors.push('Height must be between 10 and 300 mm.')
  }
  if (!Number.isFinite(diameter) || diameter < 10 || diameter > 200) {
    errors.push('Diameter must be between 10 and 200 mm.')
  }
  if (!Number.isFinite(wallThickness) || wallThickness < 0.5 || wallThickness >= diameter / 2) {
    errors.push('Wall thickness must be at least 0.5 mm and less than half the diameter.')
  }

  return { valid: errors.length === 0, errors }
}

function randomizeCylinder(
  parameters: CylinderParameterValues,
  random = Math.random,
): CylinderParameterValues {
  const diameter = Math.round(30 + random() * 150)
  const maxWallThickness = Math.max(0.5, diameter / 2 - 0.1)
  return {
    ...parameters,
    height: Math.round(30 + random() * 240),
    diameter,
    wallThickness: Math.min(maxWallThickness, Math.max(0.5, parameters.wallThickness)),
  }
}

export const parametricCylinder: ParametricModelDefinition<CylinderParameterValues> = {
  id: 'parametric-cylinder',
  name: 'Parametric Cylinder',
  category: 'Primitives',
  description: 'A hollow, printable cylinder generated by Replicad.',
  metadata: {
    name: 'Parametric Cylinder',
    category: 'Primitives',
    description: 'A hollow, printable cylinder generated by Replicad.',
  },
  parameters: cylinderParameters,
  parameterSchema: cylinderParameters,
  defaults: cylinderDefaults,
  generation: {
    backend: 'replicad',
    operation: 'parametric-cylinder',
    generate: createCylinderRequest,
  },
  validate: validateCylinder,
  generate: createCylinderRequest,
  reset: () => ({ ...cylinderDefaults }),
  randomize: randomizeCylinder,
}
